## 서울 열린데이터광장

In [72]:
from dotenv import load_dotenv
import os

load_dotenv()

SERVICE_KEY = os.getenv('SERVICE_KEY')

In [73]:
URL = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/1/100/'
URL

'http://openapi.seoul.go.kr:8088/556b6848456a757934324a50425661/json/tbLnOpendataRtmsV/1/100/'

In [74]:
import requests
import json
import pandas as pd

req = requests.get(URL)
req

In [75]:
content = req.json()
# content
result = pd.DataFrame(content['tbLnOpendataRtmsV']['row'])
result

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2024,11560,영등포구,10200,영등포동1가,1,대지,0121,0005,여의도리슈빌DS,...,20600,21.41,31.43,7.0,,,2020,오피스텔,중개거래,서울 영등포구
1,2024,11740,강동구,10900,천호동,1,대지,0090,0002,도우빌라,...,36700,48.69,46.66,-1.0,,,1991,연립다세대,중개거래,서울 강동구
2,2024,11320,도봉구,10800,도봉동,1,대지,0051,0012,중흥에스-클래스,...,55000,85.00,0.00,3.0,,,2004,아파트,중개거래,서울 도봉구
3,2024,11545,금천구,10200,독산동,1,대지,1006,0115,중앙하이빌1동2동,...,23000,28.68,14.88,4.0,,,2016,연립다세대,직거래,
4,2024,11590,동작구,10300,상도1동,1,대지,0419,0003,종로빌리지,...,40000,69.13,48.37,3.0,,,1991,연립다세대,중개거래,서울 강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024,11215,광진구,10300,구의동,1,대지,0035,0048,금화빌라,...,20000,38.18,24.90,1.0,,,1997,연립다세대,중개거래,서울 광진구
96,2024,11740,강동구,10700,암사동,1,대지,0414,0002,롯데캐슬퍼스트,...,112500,59.99,0.00,28.0,,,2008,아파트,중개거래,서울 강동구
97,2024,11410,서대문구,11900,북가좌동,1,대지,0371,0001,월드컵현대,...,81500,84.93,0.00,12.0,,,1998,아파트,중개거래,서울 서대문구
98,2024,11590,동작구,10700,사당동,1,대지,1133,0000,삼성래미안,...,134000,158.47,0.00,13.0,,,2003,아파트,중개거래,서울 동작구
99,2024,11440,마포구,10800,대흥동,1,대지,0012,0027,이대역 푸르지오 시티,...,24000,28.80,39.60,4.0,,,2013,오피스텔,중개거래,서울 마포구

In [76]:
URL = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/xml/tbLnOpendataRtmsV/1/5/'
URL

'http://openapi.seoul.go.kr:8088/556b6848456a757934324a50425661/xml/tbLnOpendataRtmsV/1/5/'

In [77]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

years            = soup.find_all('acc_year')         # 접수년월
sgg_cds          = soup.find_all('sgg_cd')           # 자치구코드
sgg_nms          = soup.find_all('sgg_nm')           # 자치구명
bjdong_cds       = soup.find_all('bjdong_cd')        # 법정동코드
bjdong_nms       = soup.find_all('bjdong_nm')        # 법정동명
land_gbns        = soup.find_all('land_gbn')         # 지번구분
land_gbn_nms     = soup.find_all('land_gbn_nm')      # 지번구분명
land_gbn_nms     = soup.find_all('land_gbn_nm')      # 지번구분명
bonbeons         = soup.find_all('bonbeon')          # 본번
bubeons          = soup.find_all('bubeon')           # 부번
bldg_nms         = soup.find_all('bldg_nm')          # 건물명
deal_ymds        = soup.find_all('deal_ymd')         # 계약일
obj_amts         = soup.find_all('obj_amt')          # 물건금액(만원)
bldg_areas       = soup.find_all('bldg_area')        # 건물면적(㎡)
tot_areas        = soup.find_all('tot_area')         # 토지면적(㎡)
floors           = soup.find_all('floor')            # 층
right_gbns       = soup.find_all('right_gbn')        # 권리구분
cntl_ymds        = soup.find_all('cntl_ymd')         # 취소일
build_years      = soup.find_all('build_years')      # 건축년도
house_types      = soup.find_all('house_type')       # 건물용도
req_gbn          = soup.find_all('req_gbn')          # 신고구분
rdealer_lawdnms  = soup.find_all('rdealer_lawdnm')   # 신고한 개업공인중개사 시군구명
year_list           = []
sgg_cd_list         = []
bldg_nm_list        = []
obj_amt_list        = []
house_type_list     = []
rdealer_lawdnm_list = []
for year, sgg_cd, bldg_nm, obj_amt, house_type, rdealer_lawdnm in zip(years, sgg_cds, bldg_nms, obj_amts, house_types, rdealer_lawdnms):
  year_list.append(year.get_text())
  sgg_cd_list.append(sgg_cd.get_text())
  bldg_nm_list.append(bldg_nm.get_text())
  obj_amt_list.append(obj_amt.get_text())
  house_type_list.append(house_type.get_text())
  rdealer_lawdnm_list.append(rdealer_lawdnm.get_text())
df = pd.DataFrame({
    "acc_year": year_list, 
    "sgg_cd": sgg_cd_list, 
    "bldg_nm" : bldg_nm_list,
    "obj_amt": obj_amt_list,
    "house_type" : house_type_list,
    "rdealer_lawdnm": rdealer_lawdnm_list
})
df

  acc_year sgg_cd    bldg_nm obj_amt house_type rdealer_lawdnm
0     2024  11560   여의도리슈빌DS   20600       오피스텔        서울 영등포구
1     2024  11740       도우빌라   36700      연립다세대         서울 강동구
2     2024  11320   중흥에스-클래스   55000        아파트         서울 도봉구
3     2024  11545  중앙하이빌1동2동   23000      연립다세대
4     2024  11590      종로빌리지   40000      연립다세대         서울 강남구

## 공공데이터 포털
- 국토교통부

In [82]:
import requests
import json
import pandas as pd
import xmltodict

PUBLIC_SERVICE_KEY = os.getenv('PUBLIC_SERVICE_KEY')

#serviceKey = '인증키 입력'
pageNo = 1 # 페이지 번호
numOfRows = 500 # 한 페이지 결과수
LAWD_CD = 11500 # 지역코드
DEAL_YMD = 202101 # 계약월
url = f'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev?serviceKey={PUBLIC_SERVICE_KEY}&pageNo={pageNo}&numOfRows={numOfRows}&LAWD_CD={LAWD_CD}&DEAL_YMD={DEAL_YMD}'
req = requests.get(url)
req

In [83]:
req.text
#contents = xmltodict.parse(req.text)
#data = pd.DataFrame(contents['response']['body']['items']['item'])

'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><header><resultCode>99</resultCode><resultMsg>SERVICE KEY IS NOT REGISTERED ERROR.</resultMsg></header></response>'

## 다중 데이터 수집

In [80]:
N = 1
data = None
for i in range(1, 3):
    URL = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/{N}/{N+999}/'
    # print(URL)
    req = requests.get(URL)
    content = req.json()
    result = pd.DataFrame(content['tbLnOpendataRtmsV']['row'])
    #print(result)
    data = pd.concat([data, result], ignore_index=True)
    N += 1000
data.head()

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2024,11560,영등포구,10200,영등포동1가,1,대지,0121,0005,여의도리슈빌DS,...,20600,21.41,31.43,7.0,,,2020,오피스텔,중개거래,서울 영등포구
1,2024,11740,강동구,10900,천호동,1,대지,0090,0002,도우빌라,...,36700,48.69,46.66,-1.0,,,1991,연립다세대,중개거래,서울 강동구
2,2024,11320,도봉구,10800,도봉동,1,대지,0051,0012,중흥에스-클래스,...,55000,85.00,0.00,3.0,,,2004,아파트,중개거래,서울 도봉구
3,2024,11545,금천구,10200,독산동,1,대지,1006,0115,중앙하이빌1동2동,...,23000,28.68,14.88,4.0,,,2016,연립다세대,직거래,
4,2024,11590,동작구,10300,상도1동,1,대지,0419,0003,종로빌리지,...,40000,69.13,48.37,3.0,,,1991,연립다세대,중개거래,서울 강남구

In [81]:
data = None
for j in range(1,3):
    url = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/{1+((j-1)*1000)}/{j*1000}'
    # url = f'http://openapi.seoul.go.kr:8088/{service_key}/json/tbLnOpendataRentV/1/1000/2023/11560'
    print(url)
    req = requests.get(url)
    content = req.json()
    con = content['tbLnOpendataRtmsV']['row']
    result = pd.DataFrame(con)
    data = pd.concat([data, result])
data = data.reset_index(drop=True)
data.head()

http://openapi.seoul.go.kr:8088/556b6848456a757934324a50425661/json/tbLnOpendataRtmsV/1/1000
http://openapi.seoul.go.kr:8088/556b6848456a757934324a50425661/json/tbLnOpendataRtmsV/1001/2000

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2024,11560,영등포구,10200,영등포동1가,1,대지,0121,0005,여의도리슈빌DS,...,20600,21.41,31.43,7.0,,,2020,오피스텔,중개거래,서울 영등포구
1,2024,11740,강동구,10900,천호동,1,대지,0090,0002,도우빌라,...,36700,48.69,46.66,-1.0,,,1991,연립다세대,중개거래,서울 강동구
2,2024,11320,도봉구,10800,도봉동,1,대지,0051,0012,중흥에스-클래스,...,55000,85.00,0.00,3.0,,,2004,아파트,중개거래,서울 도봉구
3,2024,11545,금천구,10200,독산동,1,대지,1006,0115,중앙하이빌1동2동,...,23000,28.68,14.88,4.0,,,2016,연립다세대,직거래,
4,2024,11590,동작구,10300,상도1동,1,대지,0419,0003,종로빌리지,...,40000,69.13,48.37,3.0,,,1991,연립다세대,중개거래,서울 강남구